### ISSUE TITLE
Setup - Datenstruktur für Spielbrett

### ISSUE THREAD

**Issue by Smeagle** [Smeagle/dungeongame#1]
Der erste Schritt ist, in einer Datenstruktur das Spielbrett abzubilden.
Das Spielbrett besteht aus sechsseitigen Zellen, die an ihren Kanten aneinander gelegt sind. Wie bei Siedler von Catan.
Es gibt Wandfelder und Raumfelder.
Ein Feld kennt seine jeweiligen Nachbarn, hat aber auch eine eindeutige Position (z.B. x- und y-Koordinate). Fällt euch da was gutes zu Hexfeldern ein?

**Comment by murchandamus** [comment]
Ich würde [Würfel-Koordinaten oder **Axial-Koordinaten**](http://www.redblobgames.com/grids/hexagons/#coordinates) vorschlagen. Das passt gut zu unserem Turm.

**Comment by Smeagle** [comment]
Gut

**Comment by murchandamus** [comment]
- [X] Raumfelder, Wandfelder
- [X] Sechseitige Zellen
- [X] Eindeutige Position
- [X] Kennt Nachbarn

**Comment by murchandamus** [comment]
Wenn es dir wichtig ist, könnte ich die Koordinaten von (r,q) zurück auf (q,r) wechseln. Für Wegfindung und LOS sollte das keine Änderungen erfordern, vielleicht gehen sogar die Tests einfach. Nur die Namen der Testvariablen müssten halt angepasst werden. Wie wichtig ist es dir?

**Comment by Smeagle** [comment]
Mich muss gestehen, dass es mich wirklich sehr verwirrt.
Das kommt daher, das ich gewohnt bin, dass x von links nach rechts geht und y von oben nach unten und die Koordinaten eigentlich immer (x, y) sind.
Deshalb bin ich fürs Ändern. Sorry für den Aufwand. :/

**Comment by murchandamus** [comment]
Okay, ich mach es gleich wenn ich meinen Test für die Wachen fertig geschrieben habe.

**Comment by murchandamus** [comment]
Wobei, da muss ich auch wieder Spielbretter bauen. Ich mach es zuerst und dann den Wachen-Branch weiter.

**Comment by murchandamus** [comment]
Siehe #14. Bitte bei Gelegenheit mergen.
