### ISSUE TITLE
Spielfigur v1

### ISSUE THREAD

**Issue by Smeagle** [Smeagle/dungeongame#13]
- kann vom Spieler über die Tastatur gesteuert werden (z.B über das Nummernfeld)
- hat eine feste Startposition
- kann zunächst unendlich viele Schritte gehen (weil es ja noch keine Runden etc. gibt)
- kann sich nur auf Flurfeldern bewegen (ist ja klar)
- zunächst keine weiteren Anforderungen (wie Kollisionserkennung, Sichtfeldanzeige, usw.)

**Comment by murchandamus** [comment]
Vielleicht sollte man das besser in Frontend und Backend teilen.
Verhalten der Spielfigur gehört ins Backend. Steuerung und Anzeige ins Frontend.

Frontend:
- [ ] kann vom Spieler über die Tastatur gesteuert werden (z.B über das Nummernfeld)
- [ ] Spielfigur auf Spielbrett anzeigen
- [ ] Kollisionswarnung
- [ ] Sichtfeld anzeigen 

Backend habe ich in eigene Issue umgezogen: #18

**Comment by Smeagle** [comment]
Ich schließe das Issue, weil es irgendwie das Issue "Backend: Spielfigur" kopiert.
Ein "Frontend: Spielfigur" brauchen wir eigentlich nicht mehr. Wenn doch: neues Issue.
