### ISSUE TITLE
Feld- und Wand-Texturen

### ISSUE THREAD

**Issue by Smeagle** [Smeagle/dungeongame#15]
Es sollen die Feldtexturen von Sebastian verwendet werden.
Felder bekommen die Feldtextur und Wände bekommen abhängig davon wieviele Wandfelder angrenzen die entsprechende Wandtextur.

**Comment by murchandamus** [comment]
Hast ihm schon mal erzählt was wir bisher gebastelt haben?

**Comment by Smeagle** [comment]
Ja. Aber solange man nichts sieht ist es halt nicht so spektakulär für ihn. Bin aber schon fleissig am Malen. Z.B. committe ich gleich eine texturierte Version. Ich musste natürlich alle Bild von Shub um 30 grad drehen. :/ Danke Gimp!

**Comment by Smeagle** [comment]
Ist fertig und committet. Muss ich aber nochmal etwas optimieren. Da wird zu viel während dem Malen durchgeführt, was ich eigentlich nur einmal für jedes Feld machen müsste (Textur herausfinden, Drehung herausfinden...).

**Comment by murchandamus** [comment]
Joah, aber würde gerne derart vorgehen, dass wir Funktion priorisieren und danach nur optimieren, wenn es notwendig ist. :) Zumindest bin ich bisher im Backend so vorgegangen.
