### ISSUE TITLE
Agenten auf dem Spielbrett anzeigen

### ISSUE THREAD

**Issue by Smeagle** [Smeagle/dungeongame#16]
Der Spielstatus muss die Agenten des Spiels kennen und die GUI muss diese anzeigen.

**Comment by murchandamus** [comment]
Im neuen Branch wird das Board eine Liste aller Agenten haben: zu erreichen mit Aufruf von `Gameboard.getAgents()`. Siehe Zwischenstand #17.

**Comment by Smeagle** [comment]
Agenten werden jetzt gezeichnet.
Siehe Guard für ein Beispiel wie Agent.getImage() zu implementieren ist.
Die hinzugefügten Bilder sind noch Platzhalter...
