### ISSUE TITLE
Wie wollen wir mit Git arbeiten?

### ISSUE THREAD

**Issue by Smeagle** [Smeagle/dungeongame#20]
Bis jetzt macht z.B. Mark immer einen Pull Request.
Könnten wir nicht einfach alle Pushen?
Was wäre der Nachteil? (Ich kenne mich noch nicht so gut aus...)
Auf jeden Fall hätte es den Vorteil, dass ich dei Pull Requests nicht mergen müsste.

**Comment by murchandamus** [comment]
Da ich da mehr Erfahrung mit Git habe, dachte ich dass ich dir überlasse wann du den PR mergest, weil du dann deine Sachen zuerst pushen kannst, und ich dann einfach nochmal den `origin/master` reinmerge und du dann nur auf den Knopf drücken musst. Wenn jeder pusht muss halt jeder immer den `master` wieder reinziehen um kompatibel zu sein. Also, wenn es dir lieber ist, kann ich auch gleich pushen.

**Comment by murchandamus** [comment]
@Smeagle Wenn du eine kurze Übersicht von einem übliche Git-Entwicklungsprozess sehen willst kannst du dir mal den [GitHub-Flow](https://guides.github.com/introduction/flow/) angucken.

**Comment by Smeagle** [comment]
Ich bin es halt ohne PRs gewohnt. Wegen mir können wir die weg lassen. Michael würde die auch weg lassen. Ich glaube das passt dann besser zu dem Projekt. Ich reviewe eurer Zeug ja nicht so im Detail ;).

**Comment by murchandamus** [comment]
Okay, dann ohne. :)

**Comment by murchandamus** [comment]
Verwendet ihr eigentlich einen Chat oder ähnliches? Steam und nur GitHub ist etwas klobig.
