### ISSUE TITLE
Guard findet nicht den kürzesten Weg

### ISSUE THREAD

**Issue by Monky18** [Smeagle/dungeongame#24]
![dungeongame-bug2](https://cloud.githubusercontent.com/assets/17991334/14076454/1def72c6-f4e2-11e5-8215-bf82ed9e04ec.jpg)
![dungeongame-bug2b](https://cloud.githubusercontent.com/assets/17991334/14076455/1df3e70c-f4e2-11e5-9d45-fe8317258e76.jpg)
![dungeongame-bug2c](https://cloud.githubusercontent.com/assets/17991334/14076456/1df49aee-f4e2-11e5-82bb-975149fe06b6.jpg)

**Comment by murchandamus** [comment]
Sollte repariert sein. Siehe #31.
