### ISSUE TITLE
Guard findet keinen Weg zum Wegpunkt

### ISSUE THREAD

**Issue by Monky18** [Smeagle/dungeongame#25]
Guard findet unter bestimmten Bedingungen keinen Weg zum Wegpunkt (Sackgasse in Laufrichtung)
![dungeongame-bug](https://cloud.githubusercontent.com/assets/17991334/14076490/6be2c99c-f4e2-11e5-87a6-3285863c0e53.jpg)

**Comment by murchandamus** [comment]
Ich glaube, dass ich den Bug auf meinem Branch schon gefixt habe. Gab ein Problem in der Reihenfolge in denen Felder zur Wegfindung hinzugefügt wurden.

**Comment by murchandamus** [comment]
Hatte vorhin eine Eingebung. Sollte jetzt repariert sein. Siehe #31.
