### ISSUE TITLE
Grafische Repräsentation

### ISSUE THREAD

**Issue by Smeagle** [Smeagle/dungeongame#3]
Ohne grafische Repräsentation des Brettes ist es nicht so schön :). Deshalb brauchen wir das.
Ich würde vorschlagen, dass eine GUI mit Swing etc. gebaut wird und dann das Brett in ein JPanel gezeichnet wird. Die Swing-GUI ermöglicht einfach Knöpfe etc. hinzuzufügen. Eine hübschere GUI kann man immer noch machen. Das Panel muss scrollbar sein. Das Brett sollte, wenn das Fenster maximiert ist, im Ganzen zu sehen sein. Die Austauschbarkeit der GUI sollte gegeben sein: Es sollten sich keine Spiellogik in GUI-Klassen befinden etc.
In der ersten Version reicht es die Hexfelder mit einfachen Linien abzubilden (ohne Textur etc.).

**Comment by murchandamus** [comment]
Wie gesagt, da sehe ich mich nicht so. ;)

**Comment by Smeagle** [comment]
übernehme ich
