### ISSUE TITLE
Spielziel einbauen (Ausgang, Treppe nach oben/unten oder ähnliches)

### ISSUE THREAD

**Issue by Smeagle** [Smeagle/dungeongame#33]

**Comment by murchandamus** [comment]
Es gibt bereits einen Feldtyp dafür: [Terrain.EXIT](https://github.com/Smeagle/dungeongame/blob/6ab514c9203baf38002a555ba1556b950dd1d26c/src/dg/Terrain.java#L8)

Dieser wird bei LOS oder PathFinding wie "FLOOR" behandelt.

**Comment by murchandamus** [comment]
@Smeagle: Brauchst du von GameBoard noch etwas, oder reicht das schon?

**Comment by Smeagle** [comment]
@Xekyo : Müsste reichen. Bekommst du es hin, dass auf den Ausgang nur freundliche Figuren laufen können. Weil dann können Gegner den Ausgang nicht blockieren indem sie drauf stehen, fände ich glaube ich besser.

**Comment by murchandamus** [comment]
Wachen nehmen nur FLOOR-Felder die nicht von anderen Wachen besetzt sind als erlaubte Bewegungsziele.
