### ISSUE TITLE
Verbesserung Line of Sight

### ISSUE THREAD

**Issue by Smeagle** [Smeagle/dungeongame#44]
Siehe Bild. Warum sind die Felder links unten sichtbar und das Feld dazwischen nicht?
(Ich weiß natürlich warum, aber könnte man das verbessern, dass die Line-of-Sight zusammenhängend sein muss?)

![lineofsight](https://cloud.githubusercontent.com/assets/17887905/14706572/bb0bc100-07bf-11e6-9687-061b9a22729c.png)

**Comment by murchandamus** [comment]
Da handelt es sich wohl um einen Bug. Die linken drei Felder sollten von dem Fels blockiert werden. Anscheinend habe ich einen Denkfehler in meinem Algorithmus.

Es wäre wahrscheinlich gut, dieses Beispiel als Testfall zu übernehmen und den Fehler auszumerzen.

**Comment by murchandamus** [comment]
Sollte gefixt sein in #45.
