### ISSUE TITLE
Algorithmus: Line of Sight

### ISSUE THREAD

**Issue by Smeagle** [Smeagle/dungeongame#5]
Eingabe: ein Hexfeld, eine Blickrichtung (Kante) und ein Sichtradius (180 Grad oder 360 Grad)
Ergebnis: eine Menge von Hexfeldern, die von dem gegebenen Hexfeld aus sichtbar sind. Ein Feld ist sichtbar, wenn sich von dem Mittelpunkt des gegebenen Feldes aus eine ununterbrochene Linie zu dem Mittelpunkt des jeweiligen Feldes ziehen lässt. Verläuft die die Linie genau über eine Kante, dann wird die Linie nicht unterbrochen.

Wozu ist das gut: ich kann die Liste durchlaufen und z.B. schauen, ob auf den Feldern Gegner stehen und diese anzeigen. Oder ich kann schauen, ob ein Gegner die Spielfigur sieht, wodurch sie Alarm auslöst, etc.
Dient auch dazu den "Fog of war" zu "entfernen".

**Comment by murchandamus** [comment]
Habe etwas angefangen über Line of Sight zu lesen, aber ist noch nicht implementiert. Fange mal auf dem Branch an damit rumzuexperimentieren: https://github.com/Xekyo/dungeongame/tree/dg5-Line-Of-Sight

**Comment by murchandamus** [comment]
Siehe https://github.com/Smeagle/dungeongame/pull/9
- [X] Schnitttests zwischen Strahlen und Feldern
- [X] Generierung von Sichtlinien zwischen zwei Feldern
- [X] Sichtbarkeitsprüfung von Feldern unter Beachtung von Wänden
- [X] Generierung kompletten Sichtfeldes

**Comment by murchandamus** [comment]
Denke mal, dass es fertig ist.
