### ISSUE TITLE
Algorithmus: Wegfindung

### ISSUE THREAD

**Issue by Smeagle** [Smeagle/dungeongame#6]
Eingabe: ein Startfeld, eine Blickrichtung und ein Zielfeld
Gesucht: ein Feld, das an das Startfeld angrenzt und der nächste Schritt auf dem kürzesten Weg zum Zielfeld ist. Gibt es mehrere solche Felder, dann entscheidet die Blickrichtung: das Feld gewinnt, welches weniger Drehung erfordert, um sich zu dem Feld auszurichten). Falls es immer noch mehrere solche Felder gibt, soll zufällig entschieden werden (Fällt euch noch eine deterministische Möglichkeit ein?).

Wozu: Ein Gegner bewegt sich auf eine Spielfigur oder auf einen Wegpunkt (Patrolie) zu. Oder der Spieler klickt auf ein nicht angrenzendes Feld, um sich dahin zu bewegen etc.

**Comment by murchandamus** [comment]
Würde einfach eine A*-Suche implementieren. Heuristik fürs Expandieren `min(Schritte von Ausgangsfeld + Distanz zu Zielfeld)`.

Man könnte den Wachen einen Links- oder Rechtsdrall geben, so dass sie sich immer deterministisch drehen.

**Comment by Smeagle** [comment]
Das klingt gut.
Ja, dann lassen wir sie im uhrzeigersinn drehen, falls es keine kürzeste Drehung gibt (falls es das überhaupt gibt...).

**Comment by murchandamus** [comment]
Pathfinding wurde implementiert: https://github.com/Smeagle/dungeongame/pull/8

**Comment by murchandamus** [comment]
Kann vermutlich geschlossen werden.
